main: me.PWicks23.CrazyFeet.CrazyFeet
name: CrazyFeet
version: 1.3.0
description: Walk with Style!
author: PWicks23
permissions:
    CrazyFeet.*:
        default: op
        children:
            CrazyFeet.crazyfire: true
            CrazyFeet.crazysmoke: true
            CrazyFeet.crazymagic: true
            CrazyFeet.crazypearl: true
            CrazyFeet.crazyfire.autofire: true
            CrazyFeet.crazysmoke.autosmoke: true
            CrazyFeet.crazypearl.autopearl: true
            CrazyFeet.crazymagic.automagic: true
            CrazyFeet.autodisableothers.disableall: true
            CrazyFeet.admin: true
    CrazyFeet.admin:
        default: op
        children:
            CrazyFeet.crazyfireother: true
            CrazyFeet.crazysmokeother: true
            CrazyFeet.crazypearlother: true
            CrazyFeet.crazymagicother: true
            CrazyFeet.crazyfire.autofireother: true
            CrazyFeet.crazysmoke.autosmokeother: true
            CrazyFeet.crazypearl.autopearlother: true
            CrazyFeet.crazymagic.automagicother: true
            CrazyFeet.autodisableothers: true
            CrazyFeet.autocheckothers: true
            CrazyFeet.checkothers: true
            CrazyFeet.disableothers: true

commands:
    CrazyFire:
        description: Walk on fire!
        permission: CrazyFeet.crazyfire
    CrazySmoke:
        description: Walk on smoke!
        permission: CrazyFeet.crazysmoke
    CrazyMagic:
        description: Walk on magic dust!
        permission: CrazyFeet.crazymagic
    CrazyPearl:
        description: Walk on pearls!
        permission: CrazyFeet.crazypearl
    CrazyDisable:
        description: Disable all CrazyModes!
    CrazyCheck:
        description: Check enabled CrazyFeet modes!
    CrazyFeet:
        description: CrazyFeet menu!
        aliases: crazyhelp
    CrazyAutoFire:
        description: Automatic CrazyFire on join!
        permission: CrazyFeet.crazyfire.autofire
        aliases: crazyautof
    CrazyAutoSmoke:
        description: Automatic CrazySmoke on join!
        permission: CrazyFeet.crazysmoke.autosmoke
        aliases: crazyautos
    CrazyAutoPearl:
        description: Automatic CrazyPearl on join!
        permission: CrazyFeet.crazypearl.autopearl
        aliases: crazyautop
    CrazyAutoMagic:
        description: Automatic CrazyMagic on join!
        permission: CrazyFeet.crazymagic.automagic
        aliases: crazyautom
    CrazyAutoCheck:
        description: Check enabled automatic CrazyFeet modes!
    CrazyAutoDisable:
        description: Disable all automatic CrazyFeet modes!