main: tk.acronus.CrazyFeet.CrazyFeet
name: CrazyFeet
version: 1.3.5
description: Walk with Style!
author: runescapejon
permissions:
    CrazyFeet.*:
        default: op
        children:
            CrazyFeet.crazyfire: true
            CrazyFeet.crazysmoke: true
            CrazyFeet.crazymagic: true
            CrazyFeet.crazypearl: true
            CrazyFeet.crazynote: true
            CrazyFeet.crazywitch: true
            CrazyFeet.crazyheart: true
            CrazyFeet.crazyfire.autofire: true
            CrazyFeet.crazyfire.autoHeart: true
            CrazyFeet.crazysmoke.autosmoke: true
            CrazyFeet.crazypearl.autopearl: true
            CrazyFeet.crazymagic.automagic: true
            CrazyFeet.crazynote.autonote: true
            CrazyFeet.crazywitch.autowitch: true
            CrazyFeet.crazywitch.autowitch: true
            CrazyFeet.autodisableothers.disableall: true
            CrazyFeet.admin: true
    CrazyFeet.admin:
        default: op
        children:
            CrazyFeet.crazyfireother: true
            CrazyFeet.crazyheartother: true
            CrazyFeet.crazysmokeother: true
            CrazyFeet.crazypearlother: true
            CrazyFeet.crazymagicother: true
            CrazyFeet.crazynoteother: true
            CrazyFeet.crazywitchother: true
            CrazyFeet.crazyfire.autofireother: true
            CrazyFeet.crazysmoke.autosmokeother: true
            CrazyFeet.crazypearl.autopearlother: true
            CrazyFeet.crazymagic.automagicother: true
            CrazyFeet.crazywitch.autowitchother: true
            CrazyFeet.crazywitch.autoheartother: true
            CrazyFeet.crazynote.autonoteother: true
            CrazyFeet.autodisableothers: true
            CrazyFeet.autocheckothers: true
            CrazyFeet.checkothers: true
            CrazyFeet.disableothers: true

commands:
    CrazyFire:
        description: Walk on fire!
        permission: CrazyFeet.crazyfire
    CrazySmoke:
        description: Walk on smoke!
        permission: CrazyFeet.crazysmoke
    CrazyMagic:
        description: Walk on magic dust!
        permission: CrazyFeet.crazymagic
    CrazyPearl:
        description: Walk on pearls!
        permission: CrazyFeet.crazypearl
    Crazynote:
        description: Walk on pearls!
        permission: CrazyFeet.crazyheart
    Crazyheart:
        description: Walk on HEARTS!
        permission: CrazyFeet.crazyheart
    Crazywitch:
        description: Walk on pearls!
        permission: CrazyFeet.crazypearl
    CrazyDisable:
        description: Disable all CrazyModes!
    CrazyCheck:
        description: Check enabled CrazyFeet modes!
    CrazyFeet:
        description: CrazyFeet menu!
        aliases: crazyhelp
    CrazyAutoFire:
        description: Automatic CrazyFire on join!
        permission: CrazyFeet.crazyfire.autofire
        aliases: crazyautof
    CrazyAutoHeart:
        description: Automatic CrazyHeart on join!
        permission: CrazyFeet.crazyHeart.autoHeart
        aliases: crazyautoh
    CrazyAutoSmoke:
        description: Automatic CrazySmoke on join!
        permission: CrazyFeet.crazysmoke.autosmoke
        aliases: crazyautos
    CrazyAutoPearl:
        description: Automatic CrazyPearl on join!
        permission: CrazyFeet.crazypearl.autopearl
        aliases: crazyautop
    CrazyAutoMagic:
        description: Automatic CrazyMagic on join!
        permission: CrazyFeet.crazymagic.automagic
        aliases: crazyautom
    CrazyAutonote:
        description: Automatic Crazynote on join!
        permission: CrazyFeet.crazymagic.autonote
    CrazyAutowitch:
        description: Automatic Crazynote on join!
        permission: CrazyFeet.crazymagic.autonote
    CrazyAutoCheck:
        description: Check enabled automatic CrazyFeet modes!
    CrazyAutoDisable:
        description: Disable all automatic CrazyFeet modes!