main: tk.acronus.CrazyFeet.CrazyFeet
name: CrazyFeet
version: 1.4.0
description: Walk with Style!
author: runescapejon
permissions:
    CrazyFeet.*:
        default: op
        children:
            CrazyFeet.head: true
            CrazyFeet.crazyfirehead: true
            CrazyFeet.crazyhearthead: true
            CrazyFeet.crazynotehead: true
            CrazyFeet.crazymagichead: true
            CrazyFeet.crazysmokehead: true
            CrazyFeet.crazywitchhead: true
            CrazyFeet.crazypearlhead: true
            CrazyFeet.crazyfire: true
            CrazyFeet.autofeet: true
            CrazyFeet.autohead: true
            CrazyFeet.crazysmoke: true
            CrazyFeet.crazymagic: true
            CrazyFeet.crazypearl: true
            CrazyFeet.crazynote: true
            CrazyFeet.crazywitch: true
            CrazyFeet.crazyheart: true
            CrazyFeet.crazyfire.autofire: true
            CrazyFeet.crazyfirehead.autofirehead: true
            CrazyFeet.crazyhearthead.autohearthead: true
            CrazyFeet.crazynotehead.autonotehead: true
            CrazyFeet.crazywitchhead.autowitchhead: true
            CrazyFeet.crazymagichead.automagichead: true
            CrazyFeet.crazysmokehead.autosmokehead: true
            CrazyFeet.crazypearlhead.autopearlhead: true
            CrazyFeet.crazyfire.autoHeart: true
            CrazyFeet.crazysmoke.autosmoke: true
            CrazyFeet.crazypearl.autopearl: true
            CrazyFeet.crazymagic.automagic: true
            CrazyFeet.crazynote.autonote: true
            CrazyFeet.crazywitch.autowitch: true
            CrazyFeet.crazyheart.autoheart: true
            CrazyFeet.autodisableothers.disableall: true
            CrazyFeet.admin: true
    CrazyFeet.admin:
        default: op
        children:
            CrazyFeet.head: true
            CrazyFeet.crazyfireother: true
            CrazyFeet.crazyfireheadother: true
            CrazyFeet.crazyheartother: true
            CrazyFeet.crazysmokeother: true
            CrazyFeet.crazypearlother: true
            CrazyFeet.crazymagicother: true
            CrazyFeet.autofeet: true
            CrazyFeet.autohead: true
            CrazyFeet.crazynoteother: true
            CrazyFeet.crazywitchother: true
            CrazyFeet.crazyfire.autofireother: true
            CrazyFeet.crazyfirehead.autofireheadother: true
            CrazyFeet.crazyhearthead.autoheartheadother: true
            CrazyFeet.crazysmokehead.autosmokeheadother: true
            CrazyFeet.crazymagichead.automagicheadother: true
            CrazyFeet.crazynotehead.autonoteheadother: true
            CrazyFeet.crazypearlhead.autopearlheadother: true
            CrazyFeet.crazysmoke.autosmokeother: true
            CrazyFeet.crazypearl.autopearlother: true
            CrazyFeet.crazymagic.automagicother: true
            CrazyFeet.crazywitch.autowitchother: true
            CrazyFeet.crazywitch.autoheartother: true
            CrazyFeet.crazynote.autonoteother: true
            CrazyFeet.autodisableothers: true
            CrazyFeet.autocheckothers: true
            CrazyFeet.checkothers: true
            CrazyFeet.disableothers: true

commands:
    CrazyFireHead:
        description: Fire on your head!
        permission: CrazyFeet.crazyfirehead
    CrazyHeartHead:
        description: Hearts on your head!
        permission: CrazyFeet.crazyhearthead
    CrazySmokeHead:
        permission: CrazyFeet.crazysmokehead
    CrazyNoteHead:
        permission: CrazyFeet.crazynotehead
    CrazypearlHead:
        permission: CrazyFeet.crazypearlhead
    CrazyMagicHead:
        permission: CrazyFeet.crazymagichead
    CrazyWitchHead:
        permission: CrazyFeet.crazywitchhead
    CrazyFire:
        description: Walk on fire!
        permission: CrazyFeet.crazyfire
    CrazySmoke:
        description: Walk on smoke!
        permission: CrazyFeet.crazysmoke
    CrazyMagic:
        description: Walk on magic dust!
        permission: CrazyFeet.crazymagic
    CrazyPearl:
        description: Walk on pearls!
        permission: CrazyFeet.crazypearl
    Crazynote:
        description: Walk on pearls!
        permission: CrazyFeet.crazyheart
    Crazyheart:
        description: Walk on HEARTS!
        permission: CrazyFeet.crazyheart
    Crazywitch:
        description: Walk on pearls!
        permission: CrazyFeet.crazypearl
    CrazyDisable:
        description: Disable all CrazyModes!
    CrazyCheck:
        description: Check enabled CrazyFeet modes!
    CrazyFeet:
        description: CrazyFeet menu!
        aliases: crazyhelp
    Crazyhead:
        permission: CrazyFeet.head
    Crazyautofeet:
        permission: crazyFeet.autofeet
    Crazyautohead:
        permission: crazyFeet.autohead
    CrazyAutoFire:
        description: Automatic CrazyFire on join!
        permission: CrazyFeet.crazyfire.autofire
        aliases: crazyautof
    CrazyAutoFireHead:
        description: Automatic CrazyFireHead on join!
        permission: CrazyFeet.crazyfirehead.autofirehead
        aliases: crazyautofh
    CrazyAutoheartHead:
        description: Automatic CrazyHeartHead on join!
        permission: CrazyFeet.crazyhearthead.autohearthead
        aliases: crazyautohh
    CrazyAutoNoteHead:
        permission: CrazyFeet.crazynotehead.autonotehead
    CrazyAutoMagicHead:
        permission: CrazyFeet.crazymagichead.automagichead
    CrazyAutoSmokeHead:
        permission: CrazyFeet.crazysmokehead.autosmokehead
    CrazyAutoPearlHead:
        permission: CrazyFeet.crazypearlhead.autopearlhead
    CrazyAutoWitchHead:
        permission: CrazyFeet.crazypearlhead.autowitchhead
    CrazyAutoHeart:
        description: Automatic CrazyHeart on join!
        permission: CrazyFeet.crazyHeart.autoHeart
        aliases: crazyautoh
    CrazyAutoSmoke:
        description: Automatic CrazySmoke on join!
        permission: CrazyFeet.crazysmoke.autosmoke
        aliases: crazyautos
    CrazyAutoPearl:
        description: Automatic CrazyPearl on join!
        permission: CrazyFeet.crazypearl.autopearl
        aliases: crazyautop
    CrazyAutoMagic:
        description: Automatic CrazyMagic on join!
        permission: CrazyFeet.crazymagic.automagic
        aliases: crazyautom
    CrazyAutonote:
        description: Automatic Crazynote on join!
        permission: CrazyFeet.crazynote.autonote
        aliases: crazyauton
    CrazyAutowitch:
        description: Automatic CrazyWitch on join!
        permission: CrazyFeet.crazywitch.autowitch
        aliases: crazyautow
    CrazyAutoCheck:
        description: Check enabled automatic CrazyFeet modes!
    CrazyAutoDisable:
        description: Disable all automatic CrazyFeet modes!